### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by SteveHolle** [amweiss/dark-sky-core#104]
I was looking for a real-world example of how to use the API.  I have looked through the test examples but am not sure of how to produce calls that return usable data and how to access that data.

**Comment by Sleezly** [comment]
Here’s my git repro which uses DarkSkyCore for the purpose of wrapping it all up in an adapter design pattern to insulate another service from DarkSky reliability issues and/or outages.

It’s fairly basic and straightforward. Just take a look at the client code if that’s all you’re looking for:

https://github.com/Sleezly/SkyNet

Hope this helps!

Thanks,
Leslie

________________________________

**Comment by amweiss** [comment]
Just added a simple example to the readme, take a look and see if that’s more clear for a starting point: https://github.com/amweiss/dark-sky-core
