### ISSUE TITLE
Missing support for Time Machine Request

### ISSUE THREAD

**Issue by dsoronda** [amweiss/dark-sky-core#12]
There is no support for Time Machine Request in DarkSkyService.

BuildRequestUri also need extra DateTime parameter (null for forecast).

Note: There is UnixTimeInSeconds parameter but I need it as DateTime (without extra conversion to/from Unix time). 

p.s. I'm working on this on my fork.

**Comment by amweiss** [comment]
The API requires UNIX time in seconds to make a time machine request or a string that requires time zone which is not ideal especially since there is a built in method to convert to UNIX time.

**Comment by dsoronda** [comment]
From [API specification](https://darksky.net/dev/docs/time-machine):

~~~
time required
Either be a UNIX time (that is, seconds since midnight GMT on 1 Jan 1970) or a string formatted as follows: [YYYY]-[MM]-[DD]T[HH]:[MM]:[SS][timezone]. timezone should either be omitted (to refer to local time for the location being requested), Z (referring to GMT time), or +[HH][MM] or -[HH][MM] for an offset from GMT in hours and minutes. 
~~~

IMHO, it's more logical to use
~~~csharp
DateTime? Time { get; set; }
~~~
than
~~~csharp
long? UnixTimeInSeconds { get; set; }
~~~
and let user about other things instead how to convert DateTime to Unix time.

**Comment by amweiss** [comment]
Fair enough, I've got the change ready.
