### ISSUE TITLE
Offset marked as obsolete?

### ISSUE THREAD

**Issue by Still34** [amweiss/dark-sky-core#20]
Title.
Why is it marked as obsolete? The data still exists in the JSON response and is very usable.

**Comment by amweiss** [comment]
Please see: https://darksky.net/dev/docs/response Use `timezone` instead. I'm just reflecting the official document in the annotation.

**Comment by Still34** [comment]
Ah, sorry, did not see that. Although, I feel like the `Obsolete` comment should have been more clear like the documentation. Instead of `Use Timezone instead`, maybe something like `Use of this property will almost certainly result in Daylight Saving Time bugs. Please use timezone, instead.` like the docs?

**Comment by amweiss** [comment]
Fair enough.

**Comment by amweiss** [comment]
Fixed in v3.0.0 (was also in v2.0.0 but I made a mistake and that version will cause issues).
