### ISSUE TITLE
Incorrect ExpiresDateTime conversion

### ISSUE THREAD

**Issue by Still34** [amweiss/dark-sky-core#23]
Title.
`ExpiresDateTime` seems to be returning 1970/1/1 minus whatever the target timezone is.

**Comment by amweiss** [comment]
I don't see that issue with the data I have, what location are you seeing that from?

<img width="633" alt="image" src="https://user-images.githubusercontent.com/30146/28146467-16b067b6-6748-11e7-8085-6c122204bb7d.png">

**Comment by Still34** [comment]
https://i.imgur.com/48mdRWC.png
Sundre, CA

**Comment by amweiss** [comment]
That alert is sending an expires timestamp of `0` from the API. I'm not sure what that value means, so I can't do much with it. You should be able to check for the `DateTime` being `DateTime.Min` ignoring the offset to handle this. I can try to ask the Dark Sky team what the expected logic would be.

**Comment by amweiss** [comment]
Heard back from Dark Sky:

> That sounds like a bug—the expires time should be a UNIX timestamp in the future. I think the only way this can happen is if the National Weather Service is providing bad data to us; I'll look into it and add a sanity check!

> Thanks for letting us know!

So I'm closing this issue as it seems like it's upstream and they will look into it.
