### ISSUE TITLE
Icon not returning for Currently

### ISSUE THREAD

**Issue by FreezingCode** [amweiss/dark-sky-core#26]
Under Response -> Currently, Icon always returns None, although it does show up in the response if I paste the call into the browser. Using v3.1.3

https://api.darksky.net/forecast/your-key/44.8365032,-93.2734517

![missingicon](https://user-images.githubusercontent.com/808849/33850366-4649cb36-de79-11e7-81fa-8482c26ee7fa.PNG)

![resp](https://user-images.githubusercontent.com/808849/33850533-c5d7da5a-de79-11e7-85c5-52e1e335846d.PNG)

Seems to also be true regarding Response -> Daily -> Data -> Icon.

**Comment by amweiss** [comment]
It's changed now, but if I look at tomorrow at 8am it shows the right icon. So make sure your `GetForecast` request in the program matches that URL request.
![image](https://user-images.githubusercontent.com/30146/33853066-a1d33cce-de8a-11e7-97ca-d8be613ecd1e.png)

**Comment by amweiss** [comment]
I'm running a web service with asp.net core 2.1 and DarkSkyCore 3.1.5 from NuGet and seeing Icons returned. I don't currently have a framework 4.6.1 setup so I can't verify that.
