### ISSUE TITLE
Unable to add package to .NET 4.5.2 project

### ISSUE THREAD

**Issue by jehrich** [amweiss/dark-sky-core#78]
When adding the package to a project targeting .NET Framework v4.5.2 in Visual Studio 2017, I'm getting the following error:

`Could not install package 'DarkSkyCore 5.1.13'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`			

The same happens when I try to add the most recent 3.x and 4.x versions.

**Comment by amweiss** [comment]
I've currently only targeted .NETStandard 1.3 and 2.0, so it requires .NETFramework 4.6+ per https://docs.microsoft.com/en-us/dotnet/standard/net-standard. Going back to something less than .NETSTandard 1.3 means lots of extra work for me around datetime stuff that I'd rather not do.

**Comment by jehrich** [comment]
That makes total sense. I misread it as needing .NET Framework v2.0 or higher. Thank you Adam!
