### ISSUE TITLE
Does not work on non-US user localizations

### ISSUE THREAD

**Issue by dsoronda** [amweiss/dark-sky-core#9]
Note : DarkSky API requires that latitude and longitude uses decimal dot.

So using this API client with ie. Croatian localization settings (comma for decimal separator) will generate invalid DarkSky api url like `forecast/716c78f54adfbe480b8168907f743729/42,9150,- 78,7410?&exclude=flags&extend=hourly&lang=x-pig-latin&units=si`

Also there is extra space in longitude parameter.

Suggested fix for DarkSkyServices.cs
~~~csharp
        string BuildRequestUri(double latitude, double longitude, OptionalParameters parameters)
        {

            // Fix nubers to ignore regional
            var lat = $"{latitude:###.#############}";
            var lon = $"{longitude:###.#############}";

            var queryString = new StringBuilder($"forecast/{_apiKey}/{lat},{lon}");

~~~

**Comment by dsoronda** [comment]
Note:
~~~csharp
var lat = $"{latitude:###.#############}"; // still uses regional settings :(

//Val : Value : -123,4167036709875
//My fix:  Console.WriteLine($"Invariant val: { latitude.ToString(CultureInfo.InvariantCulture.NumberFormat)}");
//Invariant val: -123.4167036709875
//With ###.############# : -123,4167036709875
~~~

**Comment by amweiss** [comment]
Yes, I discovered that. I pushed the fix last night that forces the invariant culture.
