### ISSUE TITLE
Add .net 4.6 framework support

### ISSUE THREAD

**Issue by tinohager** [amweiss/dark-sky-core#95]
It is possible to add .net46 support? I know .netstandard2.0 have this support but if i install i have many extra dlls in my project folder.

For example

- 3 files without DarkSkyCore
- 108 files with DarkSkyCore

Thanks

**Comment by amweiss** [comment]
It's set to target netstandard1.3 which is what is needed for .net46. I can add `net46` specifically and see if changes your results, but I don't have that setup anywhere to test right now.

**Comment by amweiss** [comment]
https://www.nuget.org/packages/DarkSkyCore/5.1.16 is uploaded and validating now, give it a shot and see what happens.

**Comment by tinohager** [comment]
16 files with DarkSkyCore 👍

**Comment by tinohager** [comment]
Thanks a lot!
